embedding_dimension: 50
weight_decay: 1e-08
learning_rate: 0.002
training_neg_sample_num: 8
alpha: 1
word_embedding_file: glove-wiki-gigaword-50
item_lm_len_field: item_lm_len
item_lm_field: item_lm
item_description_fields: [item_description_lm, item_genre_lm]